### ISSUE TITLE
Can we avoid calling `environ.to_config`?

### ISSUE THREAD

**Issue by vlcinsky** [hynek/environ_config#2]
Seeing your presentation from PyCon 2018 (thanks a lot for that), I jumped nto your library to test `environ_config`. It works and helps.

Anyway, I got confused a bit and will try to describe that and propose alternative approach.

# What confused me

I refer to the example in README.

First I expected, that instance of `AppConfig` class will already be populated config object, but I found, that e.g. `env` property is a `Raise` instance.

Then I understood, `environ.to_config` shall be called. At the end, the directly instanciated `AppConfig` is not what one expects.

# Proposal 1: Full initialization using `os_environ`

What about:

```python
cfg = AppConfig()
```

or with explicit os_environ:

```python
os_environ={
 "APP_ENV": "dev",
 "APP_DB_HOST": "localhost",
 "LANG": "C",
 "APP_AWESOME": "yes",
 "SECRET_YOUR_APP_DB_PASSWORD": "s3kr3t",
}  
cfg = AppConfig(os_environ=os_environ)
```

pros:
- looks very simple and intuitive
cons:
- implementation may become complex (att values may come from two sources: `environ` and specific argument directly)

# Proposal 2: Add class method `from_environ`

It would work as follows:

```python
cfg = AppConfig.from_environ()
```

or using explicit `os_environ` value:

```python
os_environ={
 "APP_ENV": "dev",
 "APP_DB_HOST": "localhost",
 "LANG": "C",
 "APP_AWESOME": "yes",
 "SECRET_YOUR_APP_DB_PASSWORD": "s3kr3t",
}  
cfg = AppConfig.from_environ(os_environ)
```

One advantage would be, direct instantiation with explicit arguments could work as expected:

```python
cfg = AppConfig(env="dev", awesome=True, db=AppConfig.DB(host="localhost", password="s3kr3t"))

```
The `from_environ` could get `kwargs` argument to allow mixed creation:

```python
cfg = AppConfig.from_environ(os_environ=os_environ, kwargs=dict(env="dev", awesome=True))
```

pros:
- easy to create `AppConfig` instance without environmental variables
- implementation would be simpler
cons:
- direct instantiation could surprise (raising Exception on missing arguments).

Expected modifications would be:
- add class method (could be very similar to existing `environ.to_config`
- modify handling of arguments without defaults not to return `Raise` instance, but really raise an exception.

# Conclusions

First, I was in favour of Proposal 1, but the Proposal 2 seems simpler to implement and in a way looks cleaner. What do you think?

**Comment by vlcinsky** [comment]
Here is modified README example with `AppConfig` class having `from_environ` class method.

If `@environ.config` could manage that, the code would be simpler.

```python
import environ
import os

# Extracts secrets from Vault-via-envconsul: 'secret/your-app':
vault = environ.secrets.VaultEnvSecrets(vault_prefix="SECRET_YOUR_APP")


@environ.config(prefix="APP")
class AppConfig:

    @environ.config
    class DB:
        name = environ.var("default_db")
        host = environ.var("default.host")
        port = environ.var(
            5432, converter=int
        )  # Use attrs's converters and validators!
        user = environ.var("default_user")
        password = vault.secret()

    env = environ.var()
    lang = environ.var(
        name="LANG"
    )  # It's possible to overwrite the names of variables.
    db = environ.group(DB)
    awesome = environ.bool_var()

    @classmethod
    def from_environ(cls, os_environ=None):
        return environ.to_config(cls, os_environ or os.environ)


os_environ = {
    "APP_ENV": "dev",
    "APP_DB_HOST": "localhost",
    "LANG": "C",
    "APP_AWESOME": "yes",  # true and 1 work too, everything else is False
    # Vault-via-envconsul-style var name:
    "SECRET_YOUR_APP_DB_PASSWORD": "s3kr3t",
}
cfg = AppConfig.from_environ(os_environ)
print("cfg", cfg)
# prints:
# AppConfig(env='dev',
#           lang='C',
#           db=AppConfig.DB(name='default_db',
#                           host='localhost',
#                           port=5432,
#                           user='default_user',
#                           password=<SECRET>),
#           awesome=True)
```

**Comment by hynek** [comment]
Thanks for the kind words!

I’m partial to Proposal 2 and I think you deduced the reasons correctly yourself – smart initializers are terrible. FWIW, `to_config` already takes an environ arg too: `to_config(config_cls, environ=os.environ):` and it would be trivial to implement `from_environ(self, environ=os.environ)` based on that. :)

**Comment by vlcinsky** [comment]
@hynek how to conclude?

Options are:
- reject the proposal, things are working well enough
- agree on the Proposal 2, then I could make PR to enhance `@environ.config` to add the `from_environ` method to the generated class

I am fine with any of these options (and I am looking forward to the new release).
